// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cacIk3FxOzrM1YjM5cz-XY1yrRx2ANs',
    appId: '1:512014486830:web:892cd575a2e72734b0bebf',
    messagingSenderId: '512014486830',
    projectId: 'todo-b955c',
    authDomain: 'todo-b955c.firebaseapp.com',
    databaseURL: 'https://todo-b955c-default-rtdb.firebaseio.com',
    storageBucket: 'todo-b955c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCPG2E4nJMSU8byF7IrrUDNUZkPogoeE',
    appId: '1:512014486830:android:6c34179ff723425db0bebf',
    messagingSenderId: '512014486830',
    projectId: 'todo-b955c',
    databaseURL: 'https://todo-b955c-default-rtdb.firebaseio.com',
    storageBucket: 'todo-b955c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxANMCk8L3ufK01tsHZyORXsMUD0qNnPw',
    appId: '1:512014486830:ios:8666edd96d638bb4b0bebf',
    messagingSenderId: '512014486830',
    projectId: 'todo-b955c',
    databaseURL: 'https://todo-b955c-default-rtdb.firebaseio.com',
    storageBucket: 'todo-b955c.appspot.com',
    iosClientId: '512014486830-nui9q5qtqn9h3s8rpo8qd0go2urjlj2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxANMCk8L3ufK01tsHZyORXsMUD0qNnPw',
    appId: '1:512014486830:ios:d6cad22644fe07d7b0bebf',
    messagingSenderId: '512014486830',
    projectId: 'todo-b955c',
    databaseURL: 'https://todo-b955c-default-rtdb.firebaseio.com',
    storageBucket: 'todo-b955c.appspot.com',
    iosClientId: '512014486830-a97ldkln2552kda3mh49sjvdoqtacbsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
